### ISSUE TITLE
initdb: error: invalid authentication method "<snip-password>" for "local" connections

### ISSUE THREAD

**Issue by OvermindDL1** [faokunega/pg-embed#1]
Getting this error upon running `PgEmbed::setup` in the current latest released version of 0.3.2:

> `initdb: error: invalid authentication method "<snip-password>" for "local" connections`

Which is odd, because why would the password be appearing as an authentication method?  Looking at the code I see:

```rust
    pub async fn init_db(&self) -> Result<bool, PgEmbedError> {
        let database_path = std::path::Path::new(&self.pg_settings.database_dir);
        if !database_path.is_dir() {
            let init_db_executable = format!("{}/bin/initdb", &self.pg_settings.executables_dir);
            let password_file_arg = format!("--pwfile={}/pwfile", &self.pg_settings.executables_dir);
            let process = Command::new(
                init_db_executable,
            )
                .args(&[
                    "-A",
                    &self.pg_settings.password,
                    "-U",
                    &self.pg_settings.user,
                    "-D",
                    &self.pg_settings.database_dir,
                    &password_file_arg,
                ])
                .spawn().map_err(|e| PgEmbedError::PgInitFailure(e))?;
            sleep(self.pg_settings.start_timeout).await;
            Ok(true)
        } else {
            Ok(false)
        }
    }
```
Which is exceptionally odd as indeed `self.pg_settings.password` is being passed into the `-A` argument for `initdb`, which should be taking an authentication method like `"scram-sha-256"` or `"md5"` or something.

As a test, changing the password to be `scram-sha-256`, thus the password being used as both the authentication type as well as the password does indeed get it working, this is quite a bit wrong and insecure however...  ^.^;

**Comment by faokunega** [comment]
Thanks for the hint. I will fix this and make an update this coming weekend.

**Comment by OvermindDL1** [comment]
Awesome, thanks much!

**Comment by faokunega** [comment]
I made an update. 
Please let me know if you are still having issues.
