### ISSUE TITLE
`PgSettings::executables_dir` and `PgSettings::database_dir` are String's

### ISSUE THREAD

**Issue by OvermindDL1** [faokunega/pg-embed#2]
`PgSettings::executables_dir` and `PgSettings::database_dir` are String's, when they should be PathBuf's.  PathBuf's are the proper type to use for filesystem paths as they can properly encode filesystem paths, which may not be UTF-8.  String's on the other hand are UTF-8 only, and thus cannot encode all filesystem paths, making this impossible to use in some data directories.  Filesystem paths should always be Path/PathBuf's, never Strings.

**Comment by OvermindDL1** [comment]
Ditto with `migration_dir` as well.

**Comment by faokunega** [comment]
Expect this to be fixed with the coming update. Thanks

**Comment by OvermindDL1** [comment]
Awesome!  Thanks much!

**Comment by faokunega** [comment]
An update has been made. Fixed with version 0.4.
