### ISSUE TITLE
Allow to reuse binaries even when persistent is disabled

### ISSUE THREAD

**Issue by nicoulaj** [faokunega/pg-embed#3]
If you want to run multiple tests in parallel, each with its own isolated database, currently there is no choice but to download+extract binaries for each test. So it would be nice if the `executables_dir` could be split in two, one for the actual executables that does not need to be clean even when `persistent=false`, and one for the runtime data.

The actual executables directory could even be relocated to something like `$XDG_CACHE_HOME/pg-embed/<version>`, to allow cross project reuse.

Thanks for the nice lib!

**Comment by faokunega** [comment]
I will follow your suggestion and relocate the executables to `$XDG_CACHE_HOME/...`.
This will be included in the coming update.
Thanks!

**Comment by nicoulaj** [comment]
For what it's wort, the [`cached_path`](https://docs.rs/cached-path/0.5.1/cached_path/) crate makes it very easy, it even does the extraction.

**Comment by faokunega** [comment]
This has been changed with v0.5.0. (View [CHANGELOG.md](https://github.com/faokunega/pg-embed/blob/master/CHANGELOG.md) for more details).
