### ISSUE TITLE
Make subprocress output configurable

### ISSUE THREAD

**Issue by nicoulaj** [faokunega/pg-embed#4]
The postgresql subcommands spam the logs quite a bit, so it would be nice to provide a way for users to handle it, eg:

- by using `log` with a configurable level
- by letting users provide their own output handler

**Comment by faokunega** [comment]
This will be changed with the coming update.
Thanks

**Comment by faokunega** [comment]
This has been changed with v0.5.0

**Comment by nicoulaj** [comment]
Working fine, thanks :)
